#!/usr/bin/env bash 
#IFS
IFS=":"

while read -r u_name pass uid gid uid_info home_d c_shell
do
	echo "The user $u_name is part of the $gid gang,\
	       > lives in $home_d and rides $c_shell.\
	      > $uid's place is protected by the passcode $pass,\
	     > more info about the user here: $uid_info"
done < /etc/passwd
